apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolodex-deployment
  namespace: rolodex-canary
  labels:
    app: rolodex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolodex
  template:
    metadata:
      labels:
        app: rolodex
    spec:
      containers:
      - name: rolodex
        image: ghcr.io/pdb64/rolodex:main
        imagePullPolicy: Always
        env:
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: rolodex-secrets
              key: discord_bot_token
        - name: DISCORD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: rolodex-secrets
              key: discord_client_id

